<script setup>
import { ref, computed, onMounted } from 'vue'
import { useAchievementStore } from '@/services/achievementStore'
import { MOCK_ALL_USERS } from '@/services/authStore'

const achievementStore = useAchievementStore()
const isLoading = ref(true)
const stats = ref({ users: { total: 0, students: 0, teachers: 0, admins: 0, active: 0, disabled: 0 }, achievements: { total: 0, pending: 0, approved: 0, rejected: 0, withFiles: 0 }, categories: [], levels: [], sources: [] })

onMounted(() => {
  setTimeout(() => {
    const all = achievementStore.getAll()
    stats.value = {
      users: { total: MOCK_ALL_USERS.length, students: MOCK_ALL_USERS.filter(u => u.role === 'student').length, teachers: MOCK_ALL_USERS.filter(u => u.role === 'teacher').length, admins: MOCK_ALL_USERS.filter(u => u.role === 'admin').length, active: MOCK_ALL_USERS.filter(u => u.status === 'active').length, disabled: MOCK_ALL_USERS.filter(u => u.status === 'disabled').length },
      achievements: { total: all.length, pending: all.filter(a => a.status === 'pending').length, approved: all.filter(a => a.status === 'approved').length, rejected: all.filter(a => a.status === 'rejected').length, withFiles: all.filter(a => a.files && a.files.length > 0).length },
      categories: ['Учебная деятельность', 'Научная деятельность', 'Внеучебная деятельность', 'Дополнительное образование', 'Развитие способностей', 'Личный вклад'].map(c => ({ name: c, count: all.filter(a => a.category === c).length })).filter(c => c.count > 0),
      levels: ['вузовский', 'региональный', 'всероссийский', 'международный'].map(l => ({ name: l, count: all.filter(a => a.level === l).length })).filter(l => l.count > 0),
      sources: ['manual', 'moodle', 'cdo'].map(s => ({ name: { manual: 'Ручной ввод', moodle: 'Moodle', cdo: 'ЦДО' }[s], count: all.filter(a => a.source === s).length })).filter(s => s.count > 0)
    }
    isLoading.value = false
  }, 400)
})

function exportPDF() { const s = stats.value; alert('Экспорт в PDF:\n\nПользователей: ' + s.users.total + '\nСтудентов: ' + s.users.students + '\nДостижений: ' + s.achievements.total + '\nПодтверждено: ' + s.achievements.approved) }
</script>
<template>
  <div class="admin-analytics">
    <div class="page-header"><div><h1>Аналитические отчёты</h1><p class="subtitle">Сводная статистика и экспорт данных системы</p></div><div class="header-actions"><button class="btn btn-primary" @click="exportPDF">Экспорт PDF</button></div></div>
    <div v-if="isLoading" class="loading-state"><div class="spinner"></div><p>Загрузка аналитики...</p></div>
    <template v-else>
      <div class="analytics-section"><h3>Пользователи</h3><div class="analytics-grid"><div class="analytics-card"><span class="ac-value">{{ stats.users.total }}</span><span class="ac-label">Всего</span></div><div class="analytics-card"><span class="ac-value blue">{{ stats.users.students }}</span><span class="ac-label">Студенты</span></div><div class="analytics-card"><span class="ac-value green">{{ stats.users.teachers }}</span><span class="ac-label">Преподаватели</span></div><div class="analytics-card"><span class="ac-value orange">{{ stats.users.admins }}</span><span class="ac-label">Администраторы</span></div><div class="analytics-card"><span class="ac-value green">{{ stats.users.active }}</span><span class="ac-label">Активные</span></div><div class="analytics-card"><span class="ac-value red">{{ stats.users.disabled }}</span><span class="ac-label">Заблокированы</span></div></div></div>
      <div class="analytics-section"><h3>Достижения</h3><div class="analytics-grid"><div class="analytics-card"><span class="ac-value">{{ stats.achievements.total }}</span><span class="ac-label">Всего</span></div><div class="analytics-card"><span class="ac-value orange">{{ stats.achievements.pending }}</span><span class="ac-label">На проверке</span></div><div class="analytics-card"><span class="ac-value green">{{ stats.achievements.approved }}</span><span class="ac-label">Подтверждено</span></div><div class="analytics-card"><span class="ac-value red">{{ stats.achievements.rejected }}</span><span class="ac-label">Отклонено</span></div><div class="analytics-card"><span class="ac-value blue">{{ stats.achievements.withFiles }}</span><span class="ac-label">С файлами</span></div></div></div>
      <div class="analytics-row"><div class="analytics-section flex-1"><h3>По категориям</h3><div class="list-table"><div v-for="cat in stats.categories" :key="cat.name" class="list-row"><span class="list-label">{{ cat.name }}</span><div class="list-bar-bg"><div class="list-bar" :style="{ width: cat.count / stats.achievements.total * 100 + '%' }"></div></div><span class="list-value">{{ cat.count }}</span></div></div></div><div class="analytics-section flex-1"><h3>По уровням</h3><div class="list-table"><div v-for="lvl in stats.levels" :key="lvl.name" class="list-row"><span class="list-label">{{ { вузовский: 'Вуз', региональный: 'Регион', всероссийский: 'РФ', международный: 'Мир' }[lvl.name] || lvl.name }}</span><div class="list-bar-bg"><div class="list-bar blue" :style="{ width: lvl.count / stats.achievements.total * 100 + '%' }"></div></div><span class="list-value">{{ lvl.count }}</span></div></div></div><div class="analytics-section flex-1"><h3>По источникам</h3><div class="list-table"><div v-for="src in stats.sources" :key="src.name" class="list-row"><span class="list-label">{{ src.name }}</span><div class="list-bar-bg"><div class="list-bar orange" :style="{ width: src.count / stats.achievements.total * 100 + '%' }"></div></div><span class="list-value">{{ src.count }}</span></div></div></div></div>
    </template>
  </div>
</template>
<style scoped>.admin-analytics { max-width: 1200px; }.page-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; flex-wrap: wrap; gap: 12px; }.page-header h1 { font-size: 26px; font-weight: 700; color: #1a1a2e; margin: 0 0 6px; }.subtitle { font-size: 14px; color: #6b7280; margin: 0; }.loading-state { display: flex; flex-direction: column; align-items: center; padding: 60px; color: #6b7280; }.spinner { width: 36px; height: 36px; border: 3px solid #e5e7eb; border-top-color: #4361ee; border-radius: 50%; animation: spin 0.7s linear infinite; margin-bottom: 12px; }@keyframes spin { to { transform: rotate(360deg); } }.analytics-section { margin-bottom: 24px; }.analytics-section h3 { font-size: 16px; font-weight: 700; color: #1a1a2e; margin: 0 0 12px; }.analytics-grid { display: grid; grid-template-columns: repeat(6, 1fr); gap: 12px; }@media (max-width: 768px) { .analytics-grid { grid-template-columns: repeat(3, 1fr); } }@media (max-width: 500px) { .analytics-grid { grid-template-columns: repeat(2, 1fr); } }.analytics-card { background: white; border-radius: 12px; padding: 16px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }.ac-value { font-size: 28px; font-weight: 800; color: #1a1a2e; display: block; }.ac-value.blue { color: #4361ee; }.ac-value.green { color: #16a34a; }.ac-value.orange { color: #d97706; }.ac-value.red { color: #dc2626; }.ac-label { font-size: 12px; color: #6b7280; margin-top: 4px; display: block; }.analytics-row { display: flex; gap: 16px; }@media (max-width: 768px) { .analytics-row { flex-direction: column; } }.flex-1 { flex: 1; }.list-table { background: white; border-radius: 12px; padding: 12px 16px; box-shadow: 0 1px 3px rgba(0,0,0,0.06); }.list-row { display: flex; align-items: center; gap: 12px; padding: 8px 0; border-bottom: 1px solid #f5f5f5; }.list-row:last-child { border-bottom: none; }.list-label { font-size: 13px; color: #374151; min-width: 80px; }.list-bar-bg { flex: 1; height: 6px; background: #e5e7eb; border-radius: 3px; overflow: hidden; }.list-bar { height: 100%; border-radius: 3px; background: #4361ee; transition: width 0.6s ease; }.list-bar.blue { background: #4361ee; }.list-bar.orange { background: #d97706; }.list-value { font-size: 14px; font-weight: 700; color: #1a1a2e; min-width: 30px; text-align: right; }.btn { display: inline-flex; align-items: center; gap: 6px; padding: 9px 18px; border-radius: 10px; font-size: 13px; font-weight: 600; border: none; cursor: pointer; transition: all 0.2s; }.btn-primary { background: #4361ee; color: white; }.btn-primary:hover { background: #3651d4; }</style>